### ISSUE TITLE
I gave myself a +1

### ISSUE THREAD

**Issue by MaximilianMeister** [lgtmco/lgtm#11]
this should not be counted IMHO if I am the author of the PR

**Comment by tboerger** [comment]
Maybe this should be made configurable.

**Comment by bradrydzewski** [comment]
this can be disabled with `self_approval_off=true` in the `.lgtm` file

**Comment by MaximilianMeister** [comment]
thanks

**Comment by tobiasKaminsky** [comment]
@bradrydzewski this is not working for us: 
https://github.com/nextcloud/server/issues/238
We tried it in https://github.com/nextcloud/server/pull/242
