### ISSUE TITLE
Support OWNERS file

### ISSUE THREAD

**Issue by benhutchins** [lgtmco/lgtm#20]
While a `MAINTAINERS` is good, this doesn't work very well for all projects. Many projects therefore use `OWNERS` files, which sometimes works by being placed in any folder to define the owners of that portion of a codebase or by using pathing within an `OWNERS` file to specify which paths they own.

https://github.com/bkeepers/OWNERS implements a pathing based top-level `OWNERS` file.

Realistically this could be merged with the existing support for the `MAINTAINERS` file, just need to use the Toml-style file and add support for defining a path or specifying file matching patterns (like `*.js`).

This would dramatically help improve the usability of LGTM, requiring changes to specific sections of the codebase to be signed off may result in several required sign offs which is ideal.

**Comment by bradrydzewski** [comment]
I would be open to adding the following fields to the `.lgtm` file:

```
from = "bkeepers/OWNERS"
path = "OWNERS"
```

The `from` field would suggest an alternate repository name from which to fetch the maintainers file. The `path` file would suggest an alternate path / filename.

Please note that I'm not personally fulfilling feature requests for the project, however, if you are willing to send a pull request based on the above recommended implementation it is something I'm open to merging.

**Comment by bradrydzewski** [comment]
> Realistically this could be merged with the existing support for the MAINTAINERS file, just need to use the Toml-style file and add support for defining a path or specifying file matching patterns (like *.js).

Sorry I forget to comment on this part. Please see the following section of the README
https://github.com/lgtmco/lgtm#development

If you are looking to extend LGTM to notify maintainers based on file type and matching patterns you might want to fork the project (feel free to rebrand as well). I published the source mostly so others could fork and extend as opposed to growing the LGTM feature set.

**Comment by bradrydzewski** [comment]
I'm closing this in favor of pluggable algorithms
https://github.com/lgtmco/lgtm/issues/32

I would prefer to expose the ability to delegate custom approval workflows to a plugin / webhook as opposed to including varying approval workflows / algorithms in the main codebase.
