### ISSUE TITLE
Prevent LGTMing myself

### ISSUE THREAD

**Issue by patrickdappollonio** [lgtmco/lgtm#33]
Hello,

I know that the maintainer list is indeed the source of truth when accepting LGTMs messages. I work in a large team where we want other people to review our job, even with one approval (one LGTM). If I set it to true, a rogue dev can LGTM himself and merge after that.

Is there any option to disable LGTMing yourself?

**Comment by bradrydzewski** [comment]
yes, in the `.lgtm` file you can add `self_approval_off = true`

**Comment by patrickdappollonio** [comment]
Thanks! Should I assume this also works for the self-hosted version? I couldn't find any references in the docs.

**Comment by bradrydzewski** [comment]
yep! self hosted and hosted service share the same code / docker image

**Comment by patrickdappollonio** [comment]
So I tried and double check in Github Enterprise and it does not work. [I was able to LGTM myself, twice](https://cloud.githubusercontent.com/assets/930925/17298521/7f8eba44-57c7-11e6-8645-ecfdeff24162.png). My `.lgtm` file looks like this:

```
approvals = 1
pattern = "(?i)LGTM"
self_approval_off = true
```
