### ISSUE TITLE
checks not done completely , when a pull request is synchronized

### ISSUE THREAD

**Issue by sukki07** [lgtmco/lgtm#39]
Scenario
create a pull request , let two approvers approve it so it is ready to merge.
Now add another commit to it , the status goes back to pending again(which is correct)
but now if any user comments anything on it , status moves to mergeable (which is incorrect , according to me , since it should again require two approvals ).

The issue is arising , since right now we call getApprovals whenever a comment is added and 
getApprovals counts ALL the comments on the PR , hence the very first comment after a new commit on a approved PR , approves it again .

One solution would be to - replace LGTM with some "DUMMY_VALUE" in all comments when a synchronized webhooks is fired .
so that it does not count them.

**Comment by bradrydzewski** [comment]
This is the intended behavior. Feel free to fork and change to meet your exact needs

**Comment by jonbodner** [comment]
I have a fork that fixes this behavior: https://github.com/lgtmeow/lgtmeow
