### ISSUE TITLE
datastore.go missing postgres driver

### ISSUE THREAD

**Issue by marcinwyszynski** [lgtmco/lgtm#43]
The driver is not registered since it's not imported. Importing `github.com/lib/pq` should do the trick.

**Comment by bradrydzewski** [comment]
postgres is not a supported driver. Even if we imported the postgres driver the sql queries and database migrations would fail, since postgres is not compatible with sqlite or mysql syntax

**Comment by marcinwyszynski** [comment]
Wouldn't it then make sense to remove all mentions of `postgres` from the code?

**Comment by bradrydzewski** [comment]
Postgres is mentioned in one line if code due to copy  / paste. References in `/vendor` cannot be removed because those references exist in our project dependencies. Feel free to send a PR to remove the reference in the case statement in `database.go` if you feel strongly about it
