### ISSUE TITLE
GitHub allows editing other users' comments

### ISSUE THREAD

**Issue by marcinwyszynski** [lgtmco/lgtm#45]
I'm wondering if the premise of basing approvals on the content of comments is a good idea. If lgtm.co is supposed to be something more than an honor system (for which you don't need a tool TBH), then being able to replace a comment like `You can push it over my cold dead body` into `LGTM mate, well done!` kind of defeats the purpose.

I was designing a similar system, and my idea was to create a DB entry for each PR, link it from a GH status and have users LGTM there.

**Comment by bradrydzewski** [comment]
> I'm wondering if the premise of basing approvals on the content of comments is a good idea. If lgtm.co is supposed to be something more than an honor system (for which you don't need a tool TBH), then being able to replace a comment like You can push it over my cold dead body into LGTM mate, well done! kind of defeats the purpose.

It is true that project owners can edit comments, but project owners can also override protected branches and force merge pull requests. I'm not sure it is within the scope of lgtm to prevent project owners from sabotaging their own project approval process. The primary goal for lgtm is to help project owners delegate approvals to community members or individuals with limited repository access, and the system is architected accordingly.

> I was designing a similar system, and my idea was to create a DB entry for each PR, link it from a GH status and have users LGTM there.

feel free to fork lgtm and modify to meet your needs or publish a competing system. This project is primarily used to support the 100+ active repositories that I maintain, and helps me delegate approvals to community members. But it certainly doesn't work as-is for everyone. I fully support community forks of this project.

**Comment by marcinwyszynski** [comment]
> I'm not sure it is within the scope of lgtm to prevent project owners from sabotaging their own project approval process.

Fair point.
