### ISSUE TITLE
Show all repositories

### ISSUE THREAD

**Issue by donny-dont** [lgtmco/lgtm#6]
Currently if you can't enable a repository it does not show up in the list. However it'd be nice to see what is actually enabled. Maybe have some different visual for the OFF where its red showing you can't add it.

**Comment by bradrydzewski** [comment]
Not all systems provide the information required to implement this visual. Specifically Bitbucket does not include repository permissions in the response. I'm not sure this will ever get ported to Bitbucket (it could)  but until we make that decision we need to keep portability in mind. For this reason we probably wouldn't implement this in the short term

**Comment by bradrydzewski** [comment]
I definitely appreciate where this issue is coming from. I just don't think it will get implemented due to lack of uniformity in permission data across providers when fetching the repository list. In the interest of keeping this issue tracker manageable I'm going to close.
