### ISSUE TITLE
Paid hosting

### ISSUE THREAD

**Issue by LinusU** [lgtmco/lgtm#8]
Is there any plans on offering paid hosting for private repositories?

**Comment by bradrydzewski** [comment]
@LinusU thanks for getting in touch. I don't have immediate plans for a paid offering. That being said we provide a very minimal docker image that is easy to setup and requires virtually no maintenance.

You can learn more about self-hosting at:
https://lgtm.co/docs/install/#installation:ee40007639ba1d9861b5cc3e7ade0aef

It is of course possible that we could offer paid plans in the future. I definitely wouldn't rule it out. If anything changes I'll post updates to this issue. Thanks!
